default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: netzone_development

test:
  <<: *default
  database: netzone_test

production:
  <<: *default
  database: netzone_production
  username: netzone
  password: <%= ENV['NETZONE_DATABASE_PASSWORD'] %>
